name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Ensure logs directory exists
        run: mkdir -p ci_cd/logs

      - name: Run linting
        run: black --check src/ 2>&1 | tee ci_cd/logs/lint_log.txt

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest

      - name: Ensure logs directory exists
        run: mkdir -p ci_cd/logs

      - name: Run unit tests
        run: pytest -v tests/unit/ > ci_cd/logs/unit_test_log.txt

      - name: Upload unit test logs
        uses: actions/upload-artifact@v3
        with:
          name: unit_test_logs
          path: ci_cd/logs/unit_test_log.txt


  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure logs directory exists
        run: mkdir -p ci_cd/logs

      - name: Set up Docker
        run: |
          docker build -t ml-model-api -f deployment/Dockerfile . 2>&1 | tee ci_cd/logs/deploy_log.txt
          docker run -d -p 5000:5000 ml-model-api
